import type { Metadata } from "next";
import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.css';
import "./globals.css";
import BootstrapCient from "@/app/components/bootstrapClient"
import { Toaster } from "react-hot-toast";
import { ClerkProvider } from "@clerk/nextjs";
import Footer from "@/app/components/footer/footer"
import Header from "@/app/components/header/header"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Night Mess",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <div id="root">
            <Toaster position="top-right" />
            <Header />
            <main>{children}</main>
            <Footer />
          </div>
          <BootstrapCient />
        </body>
      </html>
    </ClerkProvider>
  );
}
